name: CI/CD BookAPI

on:
  pull_request:
    types: [closed]
    branches: [main]
    paths:
      - 'BooksAPI/**'
      - '.github/workflows/bookapi-publish.yml'

jobs:
  build-and-push:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/bookapi:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        run: | 
          echo "${{ secrets.DOCKERHUB_TOKEN }}" \
            | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        working-directory: BooksAPI
        run: docker build -t $IMAGE_NAME .

      - name: Push Docker image
        run: docker push $IMAGE_NAME

  deploy-container:
    needs: build-and-push
    runs-on: [self-hosted, windows, x64]
    env:
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/bookapi:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull image
        shell: pwsh
        run: |
          Write-Host "Pulling image $Env:IMAGE_NAME"
          docker pull $Env:IMAGE_NAME

      - name: Remove old container (ignore if not exists)
        shell: pwsh
        continue-on-error: true
        run: |
          Write-Host "Removing any existing container named 'bookapi-container'"
          docker rm -f bookapi-container

      - name: Start new container
        shell: pwsh
        run: |
          Write-Host "Starting new container on host 8086..."
          docker run -d `
            --name bookapi-container `
            -p 8086:80 `
            -e ASPNETCORE_URLS="http://+:80" `
            $Env:IMAGE_NAME
