name: CI/CD BookAPI

on:
  pull_request:
    types: [closed]
    branches: [main]
    paths:
      - 'BooksAPI/**'
      - '.github/workflows/bookapi-publish.yml'

jobs:
  build-and-push:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/bookapi:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        run: | 
          echo "${{ secrets.DOCKERHUB_TOKEN }}" \
            | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        working-directory: BooksAPI
        run: docker build -t $IMAGE_NAME .

      - name: Push Docker image
        run: docker push $IMAGE_NAME
      